dist: xenial
language: minimal
services:
  - docker

env:
  - DOCKER_REPO=rtainjapan/rtainjapan-layouts

script:
  - docker build -t $DOCKER_REPO:$(git rev-parse --short HEAD) --build-arg TYPEKIT_ID=$TYPEKIT_ID .

deploy:
  provider: script
  script: bash scripts/docker-push
  on:
    branch: master
